version: '3.8'

services:
  strategy-notifier:
    build: .
    command: python -u bot.py
    container_name: strategy-notifier
    restart: unless-stopped
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=5ZHMz322kYNpsB1NCoBrd
      - INFLUXDB_ORG=ChanTradeOrg
      - INFLUXDB_BUCKET=ChanTradeBucket
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - SYMBOL=${SYMBOL}
      - SCHEDULE_MINUTES=${SCHEDULE_MINUTES}
    ports:
      - "5001:5001"
    volumes:
      - ./logs:/app/logs
    networks:
      - tradingnet
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=ethai
      - DOCKER_INFLUXDB_INIT_PASSWORD=ethai@123 # 请务必修改此密码
      - DOCKER_INFLUXDB_INIT_ORG=ChanTradeOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=ChanTradeBucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=5ZHMz322kYNpsB1NCoBrd # 请务必修改此Token
    networks:
      - tradingnet

volumes:
  influxdb_data:

networks:
  tradingnet:
    driver: bridge