version: '3.8'

services:
  strategy-notifier:
    # 使用当前目录下的Dockerfile进行构建
    build: .
    # 为容器命名，方便管理
    container_name: strategy-notifier
    # 设置容器在退出时总是重新启动，除非手动停止
    restart: unless-stopped
    # 将主机的.env文件加载到容器中作为环境变量
    env_file:
      - .env
    # 将主机的5001端口映射到容器的5001端口
    ports:
      - "5001:5001"
    # 设置数据卷，用于持久化日志文件
    volumes:
      # 将主机的logs目录映射到容器的/app/logs目录
      - ./logs:/app/logs